//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class sysdiagrams
{
    public string name { get; set; }
    public int principal_id { get; set; }
    public int diagram_id { get; set; }
    public Nullable<int> version { get; set; }
    public byte[] definition { get; set; }
}

public partial class TB_IMPORTANCIA
{
    public TB_IMPORTANCIA()
    {
        this.TB_PESQUISA_CLIENTE = new HashSet<TB_PESQUISA_CLIENTE>();
        this.TB_PESQUISA_CLIENTE1 = new HashSet<TB_PESQUISA_CLIENTE>();
        this.TB_PESQUISA_CLIENTE2 = new HashSet<TB_PESQUISA_CLIENTE>();
        this.TB_PESQUISA_CLIENTE3 = new HashSet<TB_PESQUISA_CLIENTE>();
        this.TB_PESQUISA_CLIENTE4 = new HashSet<TB_PESQUISA_CLIENTE>();
        this.TB_PESQUISA_CLIENTE5 = new HashSet<TB_PESQUISA_CLIENTE>();
    }

    public int ID_IMPORTANCIA { get; set; }
    public string NM_IMPORTANCIA { get; set; }

    public virtual ICollection<TB_PESQUISA_CLIENTE> TB_PESQUISA_CLIENTE { get; set; }
    public virtual ICollection<TB_PESQUISA_CLIENTE> TB_PESQUISA_CLIENTE1 { get; set; }
    public virtual ICollection<TB_PESQUISA_CLIENTE> TB_PESQUISA_CLIENTE2 { get; set; }
    public virtual ICollection<TB_PESQUISA_CLIENTE> TB_PESQUISA_CLIENTE3 { get; set; }
    public virtual ICollection<TB_PESQUISA_CLIENTE> TB_PESQUISA_CLIENTE4 { get; set; }
    public virtual ICollection<TB_PESQUISA_CLIENTE> TB_PESQUISA_CLIENTE5 { get; set; }
}

public partial class TB_PESQUISA_CLIENTE
{
    public int ID_CLIENTE { get; set; }
    public byte[] MN_EMPRESA { get; set; }
    public byte[] NM_NOME { get; set; }
    public int ID_IMP_QUALIDADE { get; set; }
    public int ID_SAT_QUALIDADE { get; set; }
    public int ID_IMP_ATENDIMENTO { get; set; }
    public int ID_SAT_ATENDIMENTO { get; set; }
    public int ID_IMP_PRAZO { get; set; }
    public int ID_SAT_PRAZO { get; set; }
    public int ID_IMP_QUALIDADE_COMERCIAL { get; set; }
    public int ID_SAT_QUALIDADE_COMERCIAL { get; set; }
    public int ID_IMP_CONHECIMENTO { get; set; }
    public int ID_SAT_CONHECIMENTO { get; set; }
    public int ID_IMP_TECNOLOGIA { get; set; }
    public int ID_SAT_TECNOLOGIA { get; set; }
    public string NM_COMENTARIO { get; set; }

    public virtual TB_IMPORTANCIA TB_IMPORTANCIA { get; set; }
    public virtual TB_IMPORTANCIA TB_IMPORTANCIA1 { get; set; }
    public virtual TB_IMPORTANCIA TB_IMPORTANCIA2 { get; set; }
    public virtual TB_IMPORTANCIA TB_IMPORTANCIA3 { get; set; }
    public virtual TB_IMPORTANCIA TB_IMPORTANCIA4 { get; set; }
    public virtual TB_IMPORTANCIA TB_IMPORTANCIA5 { get; set; }
    public virtual TB_SATISFACAO TB_SATISFACAO { get; set; }
    public virtual TB_SATISFACAO TB_SATISFACAO1 { get; set; }
    public virtual TB_SATISFACAO TB_SATISFACAO2 { get; set; }
    public virtual TB_SATISFACAO TB_SATISFACAO3 { get; set; }
    public virtual TB_SATISFACAO TB_SATISFACAO4 { get; set; }
    public virtual TB_SATISFACAO TB_SATISFACAO5 { get; set; }
}

public partial class TB_SATISFACAO
{
    public TB_SATISFACAO()
    {
        this.TB_PESQUISA_CLIENTE = new HashSet<TB_PESQUISA_CLIENTE>();
        this.TB_PESQUISA_CLIENTE1 = new HashSet<TB_PESQUISA_CLIENTE>();
        this.TB_PESQUISA_CLIENTE2 = new HashSet<TB_PESQUISA_CLIENTE>();
        this.TB_PESQUISA_CLIENTE3 = new HashSet<TB_PESQUISA_CLIENTE>();
        this.TB_PESQUISA_CLIENTE4 = new HashSet<TB_PESQUISA_CLIENTE>();
        this.TB_PESQUISA_CLIENTE5 = new HashSet<TB_PESQUISA_CLIENTE>();
    }

    public int ID_SATISFACAO { get; set; }
    public string NM_SATISFACAO { get; set; }

    public virtual ICollection<TB_PESQUISA_CLIENTE> TB_PESQUISA_CLIENTE { get; set; }
    public virtual ICollection<TB_PESQUISA_CLIENTE> TB_PESQUISA_CLIENTE1 { get; set; }
    public virtual ICollection<TB_PESQUISA_CLIENTE> TB_PESQUISA_CLIENTE2 { get; set; }
    public virtual ICollection<TB_PESQUISA_CLIENTE> TB_PESQUISA_CLIENTE3 { get; set; }
    public virtual ICollection<TB_PESQUISA_CLIENTE> TB_PESQUISA_CLIENTE4 { get; set; }
    public virtual ICollection<TB_PESQUISA_CLIENTE> TB_PESQUISA_CLIENTE5 { get; set; }
}
