//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class PESQUISACLIENTEEntities : DbContext
{
    public PESQUISACLIENTEEntities()
        : base("name=PESQUISACLIENTEEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public DbSet<sysdiagrams> sysdiagrams { get; set; }
    public DbSet<TB_IMPORTANCIA> TB_IMPORTANCIA { get; set; }
    public DbSet<TB_PESQUISA_CLIENTE> TB_PESQUISA_CLIENTE { get; set; }
    public DbSet<TB_SATISFACAO> TB_SATISFACAO { get; set; }
}
